RatesAM/urls.py
from django.contrib import admin
from django.urls import path, include

import rates

urlpatterns = [
    path('', include('rates.urls')),
    path('admin/', admin.site.urls),

]

rates/urls.py
from django.urls import path
from . import views

app_name = 'rates'
urlpatterns = [
    path('', views.index, name='index'),
    path('result', views.show_results, name='result')
]

rates/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime

now = datetime.now()
current_time = now.strftime("%d-%m-%Y %H-%M")


# Create your models here.


class Currency(models.Model):
    rub_usd_uni = models.FloatField(default=None)
    rub_eur_uni = models.FloatField(default=None)
    rub_amd_uni = models.FloatField(default=None)
    usd_amd_sas = models.FloatField(default=None)
    eur_amd_sas = models.FloatField(default=None)
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.last_update

rates/views.py
from . import models

from django.shortcuts import render


def calc(rub):
    currency = models.Currency.objects.latest('last_update')
    rates = {
        "rub_usd_uni": currency.rub_usd_uni,
        "rub_eur_uni": currency.rub_eur_uni,
        "rub_amd_uni": currency.rub_amd_uni,
        "usd_amd_sas": currency.usd_amd_sas,
        "eur_amd_sas": currency.eur_amd_sas,
    }

    calculations = {"rub": rub,
                    "usd_uni": round(rub * rates["rub_usd_uni"], 2),
                    "usd_sas": round(
                        rub * rates["rub_usd_uni"] * rates["usd_amd_sas"], 2),
                    "eur_uni": round(rub * rates["rub_eur_uni"], 2),
                    "eur_sas": round(
                        rub * rates["rub_eur_uni"] * rates["eur_amd_sas"], 2),
                    "amd_uni": round(rub * rates["rub_amd_uni"], 2)}

    calculations["rub_usd_amd"] = round(calculations['usd_sas'] / rub, 3)
    calculations["rub_eur_amd"] = round(calculations['eur_sas'] / rub, 3)
    calculations["rub_amd"] = rates["rub_amd_uni"]

    calculations["best_rate"] = max(calculations["rub_usd_amd"],
                                    calculations["rub_eur_amd"],
                                    calculations["rub_amd"])
    calculations["best_scenario"] = list(calculations.keys())[
        list(calculations.values()).index(calculations["best_rate"])]
    return calculations




def index(request):
    # create_db()
    return render(request, 'rates.html')


def show_results(request):
    rub = float(request.POST["rub_input"])
    calculations = calc(rub)

    return render(request, 'result.html', calculations)

templates/rates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'rates:result' %}" method="post">
    {% csrf_token %}
    <fieldset>
    <input type="number" name="rub_input" id="rub">
    <label for="rub">RUB</label>
    </fieldset>
    <input type="submit" value="Подтвердить">
</form>



</body>
</html>

templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
RUB = {{ rub }} <br><br>
Best scenario: <br>
{{ best_scenario }}: {{ best_rate }}<br><br>
Rates: <br>
RUB -> USD -> AMD: {{ rub_usd_amd }}<br>
RUB -> EUR -> AMD: {{ rub_eur_amd }}<br>
RUB -> AMD: {{ rub_amd }}<br><br>
Calculations:<br>
RUB -> USD (UNI): {{ usd_uni }}<br>
USD -> AMD (SAS): {{ usd_sas }}<br><br>
RUB -> EUR (UNI): {{ eur_uni }}<br>
EUR -> AMD (SAS): {{ eur_sas }}<br><br>
AMD -> UNI: {{ amd_uni }}
</body>
</html>